### ISSUE TITLE
Замечания по СРС 1 по СУБД

### ISSUE THREAD

**Issue by ns-roxer** [go-park-mail-ru/2023_2_fanaty_elki#14]
1. https://github.com/go-park-mail-ru/2023_2_fanaty_elki/blob/stage/server/db/normilized/relations.md - описание нечитабельное. Пожалуйста, отформатируйте как-то минимально.
2. https://github.com/go-park-mail-ru/2023_2_fanaty_elki/blob/stage/server/db/migrations/001_create_database.sql ВСЕ varchar переделать на TEXT, я это объяснял на лекции. https://wiki.postgresql.org/wiki/Don't_Do_This#Don.27t_use_varchar.28n.29_by_default
3. Бросается в глаза, что все названия объектов БД и аттрибутов в верхнем регистре. Хорошо, что единообразно, плохо, что в верхнем. Приведите, пожалуйста, к нижнему регистре, в стайл гайде об этом упоминается - https://www.sqlstyle.guide/#columns
4. В догонку к предыдущему пункту - а почему названия колонок в верхнем, а типы в нижнем - максимально странное решение. При чтении визуальный акцент таким образом смещается на типы полей, а идея в разделении регистров в sql в том, чтобы все зарезервинованное было в верхнем, а все свое - в нижнем.
5. public.card.card_number не должен ли быть уникальным?
6. Зачем дополнительные отступы? https://github.com/go-park-mail-ru/2023_2_fanaty_elki/blob/stage/server/db/migrations/001_create_database.sql#L7 Настройте в ide автоформатирование и не будет таких проблем.
7. https://github.com/go-park-mail-ru/2023_2_fanaty_elki/blob/stage/server/db/migrations/001_create_database.sql и https://github.com/go-park-mail-ru/2023_2_fanaty_elki/blob/stage/server/db/migrations/db.sql - один из файлов явно лишний, уберите, пожалуйста

- А еще меня очень смущает, что вы ни в одной таблице не добавили полей created_at и updated_at. Требования такого не было, поэтому это не блокер. Но рекомендую задуматься, вам как разработчикам эта информация по определенным сущностям будет очень полезна.

**Comment by tomsuliana** [comment]
Добрый день, исправили всё по Вашим замечаниям

**Comment by ns-roxer** [comment]
Смотрю - https://github.com/go-park-mail-ru/2023_2_fanaty_elki/blob/stage/server/db/migrations/db.sql
Пункт 6 не доделали до конца - с форматированием и регистром атрибутов есть недоработки:
![Скрин](https://github.com/go-park-mail-ru/2023_2_fanaty_elki/assets/4972235/6923995e-4885-48d1-807f-23f064b0c4ba)

**Comment by HallowAz** [comment]
Исправили
